Feature/dss11 sc 103170 mea use model contextual code env
dataiku/dss-plugin-model-error-analysis pull request #49
Opened 2023-02-24 08:37 UTC by alexisdurieux

Use contextual code env instead of a dedicated code environment.
This consists in 2 changes:
  * Update of `webapp.json -> useContextualCodeEnv` parameter to `true`.
  * Pull `kneed` and `mealy` dependencies locally.

Therefore the plugin now works with the contextual code with `python > 2.7` versions

2023-02-24 08:40 UTC, AgatheG commented
> Therefore the plugin now works with the contextual code with python > 2.7 versions

Why does it not work in py2?

2023-02-24 09:06 UTC, alexisdurieux commented
My bad, I updated. I meant >= 2.7.

2023-02-24 09:11 UTC, AgatheG requested changes
First quick pass through the code, did not test anything yet

We actually **do not** want to remove the files in `code-env/` as we offer a Python notebook that needs a proper code env to be run

2023-02-24 09:11 UTC, AgatheG commented on python-lib/kneed_local/knee_locator.py
> +# try:
Remove comment

2023-02-24 09:11 UTC, AgatheG commented on python-lib/kneed_local/knee_locator.py
> +    # def plot_knee_normalized(self, figsize = None, title = "Normalized Knee Point", xlabel = None, ylabel = None):
Ditto

2023-02-24 09:11 UTC, AgatheG commented on python-lib/kneed_local/knee_locator.py
> +class KneeLocator(object):
There might be some arguments/checks that are overkill here (in the end we only use the `knee` arg). Not sure if we care enought to clean up, probably not

2023-02-24 09:11 UTC, AgatheG commented on python-lib/mealy_local/error_tree.py
> +class ErrorTree(object):
[Nitpick]

Missing blank line at the end of file

2023-02-24 09:11 UTC, AgatheG commented on python-lib/mealy_local/pipeline_preprocessors.py
> +class FeatureNameTransformer(object):
We actually do not need this file for the model view

2023-03-09 14:51 UTC, alexisdurieux commented on python-lib/kneed_local/knee_locator.py
> +class KneeLocator(object):
I checked quickly and except cleaning the `@property` methods. It is probably worth keeping things as is for backwards reference.

2023-03-09 15:18 UTC, alexisdurieux commented on python-lib/mealy_local/pipeline_preprocessors.py
> +class FeatureNameTransformer(object):
I think we need it because in `dku_error_analyzer` when we `fit` and get the `error_tree` no ?

2023-04-17 16:08 UTC, AgatheG requested changes

2023-04-17 16:08 UTC, AgatheG commented on code-env/python/desc.json
> -}
Should be put back

2023-04-17 16:10 UTC, AgatheG commented
Plus indeed the imports should be updated for the unit tests

2023-04-17 16:15 UTC, AgatheG commented
The imports for the unit tests should probably be updated as well (and `mealy` can be removed from the requirements.txt of `tests/python/unit`)

2023-04-18 11:38 UTC, alexisdurieux commented on python-lib/dku_error_analysis_mpp/dku_error_analyzer.py
> -    def _get_path_to_node(self, node_id):
Added it back in parent class.

2023-04-18 11:39 UTC, alexisdurieux commented on python-lib/dku_error_analysis_utils.py
> -def format_float(number, decimals):
moved it to the other utils as it comes from mealy.

2023-04-18 13:23 UTC, AgatheG reviewed
Almost there

2023-04-18 13:23 UTC, AgatheG commented on python-lib/mealy_local/error_visualizer.py
> +from .error_analyzer import ErrorAnalyzer
```suggestion
from mealy_local.error_analyzer import ErrorAnalyzer
```

2023-04-18 13:23 UTC, AgatheG commented on code-env/python/desc.json
> +  "installJupyterSupport": false
```suggestion
  "installJupyterSupport": true
```

2023-04-18 13:23 UTC, AgatheG commented on python-lib/mealy_local/error_analyzer.py
> +        return self.pipeline_preprocessor.inverse_thresholds(self.error_tree.estimator_.tree_)
Missing blank line 👼

2023-04-18 13:23 UTC, AgatheG commented on .gitignore
> +.wlock
Blank line

2023-04-18 13:23 UTC, AgatheG commented on code-env/python/desc.json
> +  "installJupyterSupport": false
Plus blank line at end of file

2023-04-18 14:19 UTC, AgatheG approved these changes

2023-04-18 14:50 UTC, merged